application:
  name: Vidura Sense
  version: 0.1-dev
server:
  mode: debug
  host: localhost
  port: 8600
crawler: 
  user_agent: EthicalBot/0.1-dev/Email:bikashprakashdash@gmail.com
  proxies: 
    - http://test:test@localhost:3128
    - http://test:test@localhost:3129
    - http://test:test@localhost:3130