version: "3.7"

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data/standalone:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    
  mongodb:
    image: mongo:4.4.22
    container_name: "mongodb"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongodb-data:/data/db