version: "3"

services:    
  mongodb:
    image: mongo:4.4.22
    container_name: "mongodb"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - TZ=Asia/Kolkata
    volumes:
      - ./mongodb-data:/data/db

  nats-server:
    image: docker.io/bitnami/nats:latest
    container_name: "nats-server"
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    environment:
      - NATS_EXTRA_ARGS= --js
      - TZ=Asia/Kolkata

  squid-proxy:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    ports:
      - "3128:3128"
    volumes:
      - ./squid-data/squid.conf:/etc/squid/squid.conf
      - ./squid-data/passwords:/etc/squid/passwords