application:
  id: InstanceA
  version: 0.1-dev
  log:
    level: debug
    outputs: 
      - stdout
      - logs/app.log

server:
  mode: debug
  host: localhost
  port: 8600 
crawler: 
  user-agent: EthicalBot(RnD Purpose)/bikashprakashdash@gmail.com
  proxies: 
    - http://test:test@localhost:3128
data:
  mongo:
    mongo-url: mongodb://root:root@localhost:27017/vidura-iras?authSource=admin
    database: vidura-iras
    collections: 
      htmlpages: htmlpages
      feeditems: feeditems
  redis:
    redis-url: redis://localhost:6379/0
    branches:
      robots-txt: 
        name: robots-txt
        ttl: 24 #Hours
  natsio:
    nats-url: redis://localhost:6379/0
    kv-buckets:
      robots-txt: robots-txt